version: '2.1'
services:
  db:
    image: "postgres:9.6"
    environment:
      - POSTGRES_PASSWORD
    network_mode: host
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
